# Generated by Django 4.0 on 2021-12-07 19:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter city name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter country name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter company's department", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter role in the company', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter employee's first name", max_length=20)),
                ('second_name', models.CharField(help_text="Enter employee's second name", max_length=20)),
                ('birth_date', models.DateField(help_text="Choose employee's birth date")),
                ('photo', models.ImageField(upload_to='')),
                ('start_date', models.DateField(help_text="Choose employee's start date in the company")),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(help_text="Enter employee's email address", max_length=40)),
                ('description', models.CharField(help_text='Enter additional info about employee', max_length=2000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.country')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.role')),
            ],
            options={
                'ordering': ['second_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team.country')),
            ],
        ),
    ]
